"""CuteMarkets Python client.

Public entry points:

* :class:`CuteMarkets` — synchronous client.
* :class:`AsyncCuteMarkets` — asynchronous client.

Response types (typed :mod:`pydantic` models) and exceptions live under
:mod:`cutemarkets.models` and :mod:`cutemarkets.errors` respectively.
"""

from ._pagination import AsyncPage, Page, aiter_pages, iter_pages
from ._version import __version__
from .async_client import AsyncCuteMarkets
from .client import CuteMarkets
from .errors import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConfigurationError,
    CuteMarketsError,
    ForbiddenError,
    InvalidPageTokenError,
    LookbackExceededError,
    NotFoundError,
    RateLimitError,
    TransportError,
)
from .filters import ChainFilters, ContractFilters, QuoteFilters, TradeFilters
from .models import (
    Aggregate,
    Contract,
    ContractDetails,
    ContractSnapshot,
    CuteBase,
    DayBar,
    EmbeddedLastTrade,
    ExpirationsResponse,
    Greeks,
    IndicatorResult,
    IndicatorUnderlying,
    IndicatorValue,
    LastQuote,
    LastTrade,
    MacdResult,
    MacdValue,
    OpenClose,
    PaperAccount,
    PaperAccountPayload,
    PaperAccountSummary,
    PaperEquitySnapshot,
    PaperFill,
    PaperOrder,
    PaperPosition,
    Quote,
    RateLimitInfo,
    ServiceStatus,
    StockAggregate,
    StockGroupedDaily,
    StockLastQuote,
    StockLastTrade,
    StockOpenClose,
    StockQuote,
    StockRelatedTicker,
    StockSnapshot,
    StockSnapshotResponse,
    StockTicker,
    StockTickerType,
    StockTrade,
    SystemStatus,
    TickerSearchResult,
    Trade,
    UnderlyingAsset,
)

__all__ = [
    "__version__",
    "CuteMarkets",
    "AsyncCuteMarkets",
    "Page",
    "AsyncPage",
    "iter_pages",
    "aiter_pages",
    "CuteMarketsError",
    "ConfigurationError",
    "TransportError",
    "APIError",
    "BadRequestError",
    "InvalidPageTokenError",
    "AuthenticationError",
    "ForbiddenError",
    "LookbackExceededError",
    "NotFoundError",
    "RateLimitError",
    "ChainFilters",
    "ContractFilters",
    "QuoteFilters",
    "TradeFilters",
    "CuteBase",
    "RateLimitInfo",
    "ServiceStatus",
    "SystemStatus",
    "Aggregate",
    "Contract",
    "ContractDetails",
    "ContractSnapshot",
    "DayBar",
    "EmbeddedLastTrade",
    "Greeks",
    "LastQuote",
    "LastTrade",
    "OpenClose",
    "Quote",
    "Trade",
    "UnderlyingAsset",
    "StockSnapshot",
    "StockSnapshotResponse",
    "StockTicker",
    "StockTickerType",
    "StockRelatedTicker",
    "StockTrade",
    "StockLastTrade",
    "StockQuote",
    "StockLastQuote",
    "StockAggregate",
    "StockOpenClose",
    "StockGroupedDaily",
    "PaperAccount",
    "PaperAccountSummary",
    "PaperAccountPayload",
    "PaperOrder",
    "PaperPosition",
    "PaperFill",
    "PaperEquitySnapshot",
    "IndicatorResult",
    "IndicatorUnderlying",
    "IndicatorValue",
    "MacdResult",
    "MacdValue",
    "ExpirationsResponse",
    "TickerSearchResult",
]
