"""Pydantic response models for the CuteMarkets API."""

from ._base import CuteBase
from .common import RateLimitInfo, ServiceStatus, SystemStatus
from .indicators import (
    IndicatorResult,
    IndicatorUnderlying,
    IndicatorValue,
    MacdResult,
    MacdValue,
)
from .options import (
    Aggregate,
    Contract,
    ContractDetails,
    ContractSnapshot,
    DayBar,
    EmbeddedLastTrade,
    Greeks,
    LastQuote,
    LastTrade,
    OpenClose,
    Quote,
    Trade,
    UnderlyingAsset,
)
from .paper import (
    PaperAccount,
    PaperAccountPayload,
    PaperAccountSummary,
    PaperEquitySnapshot,
    PaperFill,
    PaperOrder,
    PaperPosition,
)
from .stocks import (
    StockAggregate,
    StockGroupedDaily,
    StockLastQuote,
    StockLastTrade,
    StockOpenClose,
    StockQuote,
    StockRelatedTicker,
    StockSnapshot,
    StockSnapshotResponse,
    StockTicker,
    StockTickerType,
    StockTrade,
)
from .tickers import ExpirationsResponse, TickerSearchResult

__all__ = [
    "CuteBase",
    "RateLimitInfo",
    "ServiceStatus",
    "SystemStatus",
    "Aggregate",
    "Contract",
    "ContractDetails",
    "ContractSnapshot",
    "DayBar",
    "EmbeddedLastTrade",
    "Greeks",
    "LastQuote",
    "LastTrade",
    "OpenClose",
    "Quote",
    "Trade",
    "UnderlyingAsset",
    "IndicatorResult",
    "IndicatorUnderlying",
    "IndicatorValue",
    "MacdResult",
    "MacdValue",
    "ExpirationsResponse",
    "TickerSearchResult",
    "StockSnapshot",
    "StockSnapshotResponse",
    "StockTicker",
    "StockTickerType",
    "StockRelatedTicker",
    "StockTrade",
    "StockLastTrade",
    "StockQuote",
    "StockLastQuote",
    "StockAggregate",
    "StockOpenClose",
    "StockGroupedDaily",
    "PaperAccount",
    "PaperAccountSummary",
    "PaperAccountPayload",
    "PaperOrder",
    "PaperPosition",
    "PaperFill",
    "PaperEquitySnapshot",
]
